### ISSUE TITLE
Can't install bcrypt on ubuntu

### ISSUE THREAD

**Issue by svititom** [ryanmurakami/hbfl#11]
On ubuntu 18.04, node 10.16.3. Changing the lib from bcrypt to bcryptjs in package.json seems to fix this.

Logs follow:
tom@tom-desktop:~/Documents/hbfl(master)
  ▶ sudo npm install
[sudo] password for tom: 

> bcrypt@1.0.2 install /home/tom/Documents/hbfl/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tom/Documents/hbfl/node_modules/bcrypt/build'
gyp ERR! System Linux 5.0.0-27-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/tom/Documents/hbfl/node_modules/bcrypt
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/tom/Documents/hbfl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.0.0-27-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/tom/Documents/hbfl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/tom/Documents/hbfl/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding' (1)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/tom/Documents/hbfl/node_modules/bcrypt/build'
gyp ERR! System Linux 5.0.0-27-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/tom/Documents/hbfl/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /home/tom/Documents/hbfl/node_modules/bcrypt
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.0.4 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN hbfl@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2019-09-25T14_07_33_589Z-debug.log

**Comment by svititom** [comment]
So this seems to just resolve the npm install problem, but the project doesn't run the bitnami image, since it's on node 12

**Comment by ryanmurakami** [comment]
Hi Tomas,

Yeah, I probably need to update the bcrypt stuff, as it's changed in the last few years. I'm not sure why it isn't running on the bitnami image. I'll need to check on that.

**Comment by ryanmurakami** [comment]
I'll be updating this course in the next month or so, and so this issue will be resolved.
