### ISSUE TITLE
createRecordSet not found

### ISSUE THREAD

**Issue by tony2gb** [ryanmurakami/hbfl#16]
C:\tony-aws-\hbfl-master\scripts\module_06>node create-route53-recordset.js
(node:9008) UnhandledPromiseRejectionWarning: TypeError: route53.createRecordSet is not a function
    at C:\tony-aws-\hbfl-master\scripts\module_06\create-route53-recordset.js:47:13
Thanks

**Comment by ryanmurakami** [comment]
Hi Tony, looks like this is an issue with your code, but I don't have enough to go on here. Can you paste the contents of your file?

Thanks!

**Comment by tony2gb** [comment]
Hi Ryan,
I do not see this function createRecordSet in aws js sdk api document.
Thanks,tony
===error===========C:\tony-aws-\hbfl-master\scripts\module_06>node create-route53-recordset-andy1.js(node:7720) UnhandledPromiseRejectionWarning: TypeError: route53.createRecordSet is not a function    at C:\tony-aws-\hbfl-master\scripts\module_06\create-route53-recordset-andy1.js:40:13    at new Promise (<anonymous>)    at createRecordSet (C:\tony-aws-\hbfl-master\scripts\module_06\create-route53-recordset-andy1.js:39:10)    at Object.<anonymous> (C:\tony-aws-\hbfl-master\scripts\module_06\create-route53-recordset-andy1.js:11:1)    at Module._compile (internal/modules/cjs/loader.js:959:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)    at Module.load (internal/modules/cjs/loader.js:815:32)    at Function.Module._load (internal/modules/cjs/loader.js:727:14)    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)    at internal/main/run_main_module.js:17:11(node:7720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)(node:7720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
===error end======
====code==========// Importsconst AWS = require('aws-sdk')
AWS.config.update({ region: 'us-east-1' })
// Declare local variablesconst route53=new AWS.Route53()
const hzId = 'hostedzone/ZYXOKJHOE5BA'
createRecordSet(hzId).then(data => console.log(data))
function createRecordSet (hzId) {  // TODO: Create params const  // Link to ELB Regions:  // https://docs.aws.amazon.com/general/latest/gr/rande.html#elb_region    const params={   HostedZoneId:hzId,   ChangeBatch: {   Changes: [    { Action: 'CREATE', ResourceRecordSet: { Name: 'hbfltochenv3.onlinev3', Type: 'A', AliasTarget: { DNSName: 'pizza-loaderb-1333129394.us-east-1.elb.amazonaws.com', EvaluateTargetHealth: false, HostedZoneId: 'Z35SXDOTRQ7X7K' } }        }   ]   }  }
  return new Promise((resolve, reject) => {    route53.createRecordSet(params,(err,data)=>{ if(err) reject(err) else resolve(data)   }  )  })}
===============code end===========


    On Thursday, January 9, 2020, 10:05:43 PM EST, Ryan Lewis <notifications@github.com> wrote:  
 
 
Hi Tony, looks like this is an issue with your code, but I don't have enough to go on here. Can you paste the contents of your file?

Thanks!

**Comment by ryanmurakami** [comment]
Hi Tony, got it. The function you should be using is changeResourceRecordSets: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#changeResourceRecordSets-property

**Comment by tony2gb** [comment]
Thank you Ryan! it works
    On Thursday, January 9, 2020, 11:43:47 PM EST, Ryan Lewis <notifications@github.com> wrote:  
 
 
Hi Tony, got it. The function you should be using is changeResourceRecordSets: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#changeResourceRecordSets-property

**Comment by ryanmurakami** [comment]
Glad to hear it!
