### ISSUE TITLE
Sample from Pluralsight course (codepipeline-hbfl) is missing 

### ISSUE THREAD

**Issue by hoatran888** [ryanmurakami/hbfl#18]
Hi,

I follow your lessson in Pluralsight about cloudformation for CI/CD, but i could not find the sample here eg. hbfl-pipeline.template.yaml
Could you please attach it here?

Thanks,
Xuan (iview888@gmail.com)

**Comment by ryanmurakami** [comment]
Hi Xuan,

Sorry for the confusion. All the code for that course is in this repo: https://github.com/ryanmurakami/codepipeline-hbfl

You'll find the file you're looking for in the `.aws` folder.

Thanks!
Ryan

**Comment by hoatran888** [comment]
Hi Mr. Ryan,

I got it.
Thank for the lesson.
Regards,
Xuan

**Comment by hoatran888** [comment]
Hi Mr, Ryan,

When i run your template hbfl-pipeline.template, i encounter the error as
shown:

The following resource(s) failed to create: [HbflPipelineServiceRolePolicy,
HbflPipelineArtifactStore]. . Rollback requested by user

Could you advise how to fix it?
Thanks,
Xuan

**Comment by hoatran888** [comment]
Hi,

I also taking your course on the AWS Desiging and Developing from the
Pluralsight, do you have
a sample that i can download?

Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

The code for that course is this repo ([hbfl](https://github.com/ryanmurakami/hbfl)). You can also download all the exercise files in Pluralsight under the 'Exercise Files' tab. 

What command are you using to run the `hbfl-pipeline.template` file? Also, is there a more specific error in the 'Events' tab in CloudFormation? I'm not sure what it could be based on the error you shared.

Let me know,
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

I use these two commands to run your sample:

1- sam package --template-file hbfl-pipeline.yaml --s3-bucket xt-bucket
--output-template-file package.yaml
2- sam deploy --template-file
C:\Users\pcapps59\pluralsight\ryanmurakami\codepipeline-hbfl\.aws\package.yaml
--stack-name hbfl-stack --capabilities CAPABILITY_NAMED_IAM

And I received this error:

        Deploying with following values
        ===============================
        Stack name                 : hbfl-stack
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {}
Initiating deployment
=====================
Waiting for changeset to be created..
CloudFormation stack changeset
------------------------------------------------------------------------------------------------------------------------------------------------
Operation
LogicalResourceId                                ResourceType
------------------------------------------------------------------------------------------------------------------------------------------------
+ Add
HbflBuildProject                                 AWS::CodeBuild::Project
+ Add
HbflCodeBuildServiceRolePolicy                   AWS::IAM::ManagedPolicy
+ Add
HbflCodeBuildServiceRole                         AWS::IAM::Role
+ Add
HbflPipelineArtifactStore                        AWS::S3::Bucket
+ Add
HbflPipelineServiceRolePolicy                    AWS::IAM::ManagedPolicy
+ Add
HbflPipelineServiceRole                          AWS::IAM::Role
+ Add
HbflPipeline                                     AWS::CodePipeline::Pipeline
+ Add
HbflTestProject                                  AWS::CodeBuild::Project
------------------------------------------------------------------------------------------------------------------------------------------------
Changeset created successfully.
arn:aws:cloudformation:us-east-1:204378596018:changeSet/samcli-deploy1587506426/16af8900-1d8f-438f-9302-5fc82e09de07

2020-04-21 18:00:37 - Waiting for stack create/update to complete
CloudFormation events from changeset
---------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                      ResourceType
LogicalResourceId                   ResourceStatusReason
---------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
CREATE_IN_PROGRESS                  AWS::S3::Bucket
HbflPipelineArtifactStore           -
CREATE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       Resource creation Initiated
CREATE_FAILED                       AWS::S3::Bucket
HbflPipelineArtifactStore           hbfl-pipeline-cf-artifact-store

already exists
CREATE_FAILED                       AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       Resource creation cancelled
ROLLBACK_IN_PROGRESS                AWS::CloudFormation::Stack
hbfl-stack                          The following resource(s) failed

to create:

[HbflPipelineServiceRolePolicy,

HbflPipelineArtifactStore]. .

Rollback requested by user.
DELETE_COMPLETE                     AWS::S3::Bucket
HbflPipelineArtifactStore           -
DELETE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
DELETE_COMPLETE                     AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
ROLLBACK_COMPLETE                   AWS::CloudFormation::Stack
hbfl-stack                          -
---------------------------------------------------------------------------------------------------------------------------------------------
Error: Failed to create/update the stack: hbfl-stack, Waiter
StackCreateComplete failed: Waiter encountered a terminal failure state

Please advise.
Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

Sorry about that. I need to make an update to my course because of that error. The issue is a non-unique S3 bucket name. In your `hbfl-pipeline.template` file, change the value on [line 99](https://github.com/ryanmurakami/codepipeline-hbfl/blob/c4c23162f5ae354c0af46e810176f4acdf54db36/.aws/hbfl-pipeline.template#L99) to something unique. Then it should work.

Thanks,
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

After changing the line 90 to point to my xt-bucket, i still receive this
error:

             RunOrder: 1
            -
              Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ElasticBeanstalk
              InputArtifacts:
                -
                  Name: BuildArtifact
              Configuration:
                ApplicationName: hbfl
                EnvironmentName: prod
              RunOrder: 2

  HbflPipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: xt-bucket
      # BucketName: .aws/hbfl-pipeline.template
  HbflBuildProject:
    Type: AWS::CodeBuild::Project

sam deploy --template-file
C:\Users\pcapps59\pluralsight\ryanmurakami\codepipeline-hbfl\.aws\package.yaml
--stack-name hbfl-stack --capabilities CAPABILITY_NAMED_IAM

        Deploying with following values
        ===============================
        Stack name                 : hbfl-stack
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides        : {}

Initiating deployment
=====================

Waiting for changeset to be created..

CloudFormation stack changeset
---------------------------------------------------------------------------------------------------------------------------------------------
Operation                                       LogicalResourceId
                    ResourceType
---------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                           HbflBuildProject
                     AWS::CodeBuild::Project
+ Add
HbflCodeBuildServiceRolePolicy                  AWS::IAM::ManagedPolicy
+ Add                                           HbflCodeBuildServiceRole
                     AWS::IAM::Role
+ Add                                           HbflPipelineArtifactStore
                    AWS::S3::Bucket
+ Add
HbflPipelineServiceRolePolicy                   AWS::IAM::ManagedPolicy
+ Add                                           HbflPipelineServiceRole
                    AWS::IAM::Role
+ Add                                           HbflPipeline
                     AWS::CodePipeline::Pipeline
+ Add                                           HbflTestProject
                    AWS::CodeBuild::Project
---------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully.
arn:aws:cloudformation:us-east-1:204378596018:changeSet/samcli-deploy1587641201/175d0617-dad5-42e0-a8b5-cb9cf89e79f7


2020-04-23 07:26:47 - Waiting for stack create/update to complete

CloudFormation events from changeset
---------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                      ResourceType
 LogicalResourceId                   ResourceStatusReason
---------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
CREATE_FAILED                       AWS::S3::Bucket
HbflPipelineArtifactStore           xt-bucket already exists
CREATE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       Resource creation Initiated
CREATE_IN_PROGRESS                  AWS::S3::Bucket
HbflPipelineArtifactStore           -
CREATE_FAILED                       AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       Resource creation cancelled
ROLLBACK_IN_PROGRESS                AWS::CloudFormation::Stack
 hbfl-stack                          The following resource(s) failed

                                to create:

                                [HbflPipelineServiceRolePolicy,

                                HbflPipelineArtifactStore]. .

                                Rollback requested by user.
DELETE_COMPLETE                     AWS::S3::Bucket
HbflPipelineArtifactStore           -
DELETE_IN_PROGRESS                  AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
DELETE_COMPLETE                     AWS::IAM::ManagedPolicy
HbflPipelineServiceRolePolicy       -
ROLLBACK_COMPLETE                   AWS::CloudFormation::Stack
 hbfl-stack                          -
---------------------------------------------------------------------------------------------------------------------------------------------
Error: Failed to create/update the stack: hbfl-stack, Waiter
StackCreateComplete failed: Waiter encountered a terminal failure state

Please advise.
Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

It says 'xt-bucket' already exists. You'll need to give the bucket a different name, because S3 bucket names have to be globally unique. Try adding some more words to the bucket name and trying again.

**Comment by hoatran888** [comment]
Hi Ryan,

Yes after I changed to the new s3 bucket. It is working now.
So now every time I checked in new code to code commit, the code pipe line
will run?
Sorry to ask you since this is the first time I learn code pipe line.

Thanks,
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

The build process is crashed and output this error:
































































Test Suites: 1 failed, 1 total
80 Tests:       1 failed, 2 passed, 3 total
81 Snapshots:   0 total
82 Time:        1.219s
83 Ran all test suites.
84 npm ERR! Test failed.  See above for more details.
85
86 [Container] 2020/04/24 19:38:11 Command did not exit successfully npm
test exit status 1
87 [Container] 2020/04/24 19:38:11 Phase complete: BUILD State: FAILED
88 [Container] 2020/04/24 19:38:11 Phase context status code:
COMMAND_EXECUTION_ERROR Message: Error while executing command: npm test.
Reason: exit status 1
89 [Container] 2020/04/24 19:38:11 Entering phase POST_BUILD
90 [Container] 2020/04/24 19:38:11 Running command echo Tests completed on
`date`
91 Tests completed on Fri Apr 24 19:38:11 UTC 2020
92
93 [Container] 2020/04/24 19:38:11 Phase complete: POST_BUILD State:
SUCCEEDED
94 [Container] 2020/04/24 19:38:11 Phase context status code:  Message:
95
Please advise also do I need to use webpack for this ci/cd?

Thanks,
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

Also I could not find the Lambda function resource in your
hbfl-pipeline.template. Is your project not using Lambda function
and events are used to trigger your lambda function?

Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

Glad you got it working! Yes, the pipeline will run every time there's a merge to master. Yes, the test is supposed to fail the first time, the video will show you how to fix it. For the lambda function, the video shows you how to write it. 

Thanks!
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

Thanks again for your help.

Regards,
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

I fixed the test as shown in your video. The pipeline is passing the test.
Since I do not use web deployments, I do not use elastic bean and webpack.
Again I go over all your steps from manual to using cloudformation, nowhere
I can find the Lambda function in your cloudformation that
is created.
Is it possible to create a Lambda function from your cloudformation? Can
you give me an example?
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

About the Elastic bean, using this command:
aws cloudformation create-stack --stack-name hbfl-eb --template-body
file://hbfl-eb-app.template.yaml --capabilities CAPABILITY_IAM

I encountered this error:

[image: image.png]
My question is that what command you use to create this eb stack and what
the stack name is?
I am looking forward to hearing from you.

Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

We don't create the lambda with CloudFormation in the course, just manually by hand. I don't have an example of creating a lambda with CloudFormation handy, but I'm sure you could find an example somewhere.

I wasn't able to see the error, it just shows [image: image.png]. The command to create the elastic beanstalk is what you added with just one change:
```sh
aws cloudformation create-stack --stack-name hbfl-eb --template-body
file://hbfl-eb-app.template --capabilities CAPABILITY_IAM
```
Try that and see if it works. The stack name is `hbfl-eb`.

**Comment by hoatran888** [comment]
Hi Ryan,

Thanks for advise.

Regards,
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

I am taking your course on the Pluralsight, when i go the Lambda function
trying to
read the code, I encounter this error message:

The deployment package of your Lambda function
"trash-panda-buffet-dev-index" is too large to enable inline code editing.
However, you can still invoke your function.

Could you please advise how to upload this package to AWS?

Thank you,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

Usually that appears because of the number of dependencies have been added to the Lambda function. This isn't an error. You just can't view the code in the browser. You can modify it locally and then re-upload as needed. 

Does that help?

Thanks,
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

I am afraid you forget me.

Can you just direct me to the source that help me to solve this problem?

Thanks,
Xuan
---------- Forwarded message ---------
From: hoa tran <iview888@gmail.com>
Date: Thu, Apr 30, 2020 at 4:46 PM
Subject: AWS Developer: Serverless Architecture and Monitoring
To: ryanmurakami/hbfl <
reply@reply.github.com>


Hi Ryan,

I am taking your course on the Pluralsight, when i go the Lambda function
trying to
read the code, I encounter this error message:

The deployment package of your Lambda function
"trash-panda-buffet-dev-index" is too large to enable inline code editing.
However, you can still invoke your function.

Could you please advise how to upload this package to AWS?

Thank you,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

I responded, but then re-read your original message. It looks like you've moved on to the other course. The source for that lambda function is here: https://github.com/ryanmurakami/trash-panda-buffet/blob/master/src/lambda/static.js

It looks like you already uploaded the lambda correctly. When the lambda code is too big, you can only modify it locally and then re-upload. What problem are you having?

Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

Since the lambda code is too big, i could not modify the code, and run it
from the cloud.
Is there a way to upload the big lambda code to the cloud so that I am able
to modify and run it.

Thanks to reply.
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

You should be able to run the lambda, size doesn't matter there. If you need to modify the code, you would modify it locally and then run `npm run deploy` again to deploy it out. Is that giving you some error?

Thanks,
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,
No it does not give me error.
Yes i know i can deploy again but it takes time whereas i see the code in
browser i can modify the code and kick start the program.
So there is no tool to upload big Zip file to the Aws cloud?
Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

Got it. No, once a Lambda function has dependencies, you can no longer modify it in the browser. Unfortunately, you have to modify locally and then deploy it. Sorry!

Ryan

**Comment by hoatran888** [comment]
Thanks Ryan.

**Comment by ryanmurakami** [comment]
No problem! Let me know if you have anymore questions!

**Comment by hoatran888** [comment]
HI Ryan,

How are you?

I use SAM platform to develop my AWS app:
  1- i use sam package ....> to create a package
   2- then i use sam deploy .. > to push to the cloud

Everything is working, now i change my code, and update version codecommit,
my question is that "do i have to restart
everything" follow step 1 and 2.? Since I update using codecommit, but the
program seems not working like before.

Thanks,
Xuan

**Comment by hoatran888** [comment]
(Cont.)

That is the reason I'd like to have my codes uploaded to AWS, so i just
edit it from the cloud and invoke it.

**Comment by hoatran888** [comment]
Hi Ryan,

Please ignore the previous email, i'd like to ask this question:
i define a resource like sqs in the cloudformation, how can i reference it
from my lambda function?

Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Hi Xuan,

If you create the SQS and lambda function in the same stack, you can just add a reference. If they are not in the same there are two ways. 
1. You could export the SQS ARN:
  a. Output the ARN for the SQS queue from your CloudFormation stack
  b. In your lambda function, use the `listExports` function from the AWS SDK to find the output value.
2. Add the SQS ARN as an environment variable in the Lambda function. (you would do this by hand)

Let me know if you have anymore questions!
Ryan

**Comment by hoatran888** [comment]
Hi Ryan,

Thanks so much for your help. However i can't product the good result. Here
is my code:

const AWS = require('aws-sdk');
AWS.config.update({region: 'us-east-1'});

const sqs = new AWS.SQS({apiVersion: '2012-11-05'});

let queueUrl =
'arn:aws:sqs:us-east-1:204378596018:auto-api-c24-step-commands-queue';

    var params = {
      MessageBody: myData,
      QueueUrl: queueUrl
    };
    // make sure queue exist
    sqs.sendMessage(params, function(err, data) {
      if (err) {
        console.log('Error', err.stack);
      } else {
        console.log('Success', data);
      }
    });

And this is the error when i run program using (sam logs -n <myfunction>
--stack-name my stack --tail

2020/05/08/[$LATEST]b28a8af0cc864c799eab86246bd77e81
2020-05-08T22:41:07.719000 2020-05-08T22:41:07.719Z        705179a4-cca8-4
                        INFO    Error UnknownEndpoint: Inaccessible host:
`arn'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR
(/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners
(/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit
(/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit
(/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error
(/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:333:22)
It does not regcognise "arn".

In my cloudformation the sqs is defined as shown:

  AutoApiSqsQueue:
    # Description: where lambda write to and trigger another lambda
    DependsOn: AutoApiStepFtnRole
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 10
      QueueName: !Sub "${AppName}-step-commands-queue"
      Tags:
        - Key: PROJECT
          Value: CONNECT24
        - Key: TYPE
          Value: APPLICATION
        - Key: COMPONENT
          Value: MICROSERVICE

What did i do wrong here?

Please advise.
Thanks again,
Xuan

**Comment by hoatran888** [comment]
Hi Ryan,

I was wrong. This is how I fix:
[template.yaml]
        Variables:

# SQS_NAME: !Sub
arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${AppName}-step-commands-queue
          SQS_NAME: !Ref AutoApiSqsQueue
[myLambda]
let queueUrl = process.env.SQS_NAME;
    var params = {
      MessageBody: myData,
      QueueUrl: queueUrl
    };
    // make sure queue exist
    sqs.sendMessage(params, function(err, data) {
      if (err) {
        console.log('Error', err.stack);
      } else {
        console.log('Success', data);
      }
    });



It is working fine.

Thanks for your advice.

Xuan
