### ISSUE TITLE
Poilcy faild to create

### ISSUE THREAD

**Issue by hoatran888** [ryanmurakami/hbfl#19]
Hi Mr, Ryan,

When i run your template hbfl-pipeline.template, i encounter the error as shown:

The following resource(s) failed to create: [HbflPipelineServiceRolePolicy, HbflPipelineArtifactStore]. . Rollback requested by user

Could you advise how to fix it?
Thanks,
Xuan

**Comment by ryanmurakami** [comment]
Going to go ahead and close this since we continued the discussion in another issue.
