### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by salehsub90** [ryanmurakami/hbfl#2]
> bcrypt@1.0.2 install C:\Users\Saleh\hbfl\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Saleh\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gypgyp ERR!  stackERR!     at ChildProcess.exithandler (child_process.js:289:12)
gyp configure error
ERR!gyp  stackERR!     at ChildProcess.emit (events.js:182:13)
 gypstack  Error: Command failed: C:\Users\Saleh\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
ERR!gyp stack      at maybeClose (internal/child_process.js:962:16)
ERR!gyp  stackERR!   File "<string>", line 1
 gypstack      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
ERR!gyp  ERR!stack      import sys; print "%s.%s.%s" % sys.version_info[:3];
Systemgyp Windows_NT 10.0.17134
 gypERR!  stackERR!                                ^
 gypcommand  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Saleh\\hbfl\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\Saleh\\hbfl\\node_modules\\bcrypt\\lib\\binding"
ERR!gyp  stackERR! SyntaxError: invalid syntax
 gypcwd  C:\Users\Saleh\hbfl\node_modules\bcrypt
gypERR! ERR!  stacknode -v
 v10.13.0
gypgyp  ERR!ERR!  stacknode-gyp -v     at ChildProcess.exithandler (child_process.js:289:12)
 v3.8.0
gypgyp ERR!  ERR!stack      at ChildProcess.emit (events.js:182:13)
not okgyp
 ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gypgyp  ERR!ERR!  build errorstack
     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp gypERR!  ERR!stack  Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Saleh\hbfl\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Saleh\hbfl\node_modules\bcrypt\lib\binding' (1)
Systemnode-pre-gyp Windows_NT 10.0.17134
 gyp ERR! ERR!stack      at ChildProcess.<anonymous> (C:\Users\Saleh\hbfl\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
commandnode-pre-gyp "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Saleh\\hbfl\\node_modules\\bcrypt\\lib\\binding\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\Saleh\\hbfl\\node_modules\\bcrypt\\lib\\binding"
 gypERR!  stackERR!     at ChildProcess.emit (events.js:182:13)
 node-pre-gypcwd  C:\Users\Saleh\hbfl\node_modules\bcrypt
gypERR!  ERR!stack      at maybeClose (internal/child_process.js:962:16)
node -vnode-pre-gyp v10.13.0
 ERR!gyp  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
 node-pre-gypnode-gyp -v  v3.8.0
ERR!gyp  SystemERR! Windows_NT 10.0.17134
 node-pre-gypnot ok
 ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Saleh\\hbfl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Saleh\hbfl\node_modules\bcrypt
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Saleh\hbfl\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Saleh\hbfl\node_modules\bcrypt\lib\binding' (1)
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.0.4 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN hbfl@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Saleh\AppData\Roaming\npm-cache\_logs\2018-11-05T10_58_29_684Z-debug.log

Saleh@DESKTOP-UEISOV8 MINGW64 ~/hbfl (master)
$

**Comment by ryanmurakami** [comment]
It looks like `bcrypt` v1.0.3 is only compatible with Node.js v8 [link](https://www.npmjs.com/package/bcrypt). Can you try downgrading to Node 8 and try again?
