### ISSUE TITLE
Running node create-ec2-instance.js Throws error

### ISSUE THREAD

**Issue by maniklamba20** [ryanmurakami/hbfl#20]
'There were 2 validation errors:\n* MissingRequiredParameter: Missing required key \'GroupName\' in params\n* UnexpectedParameter: Unexpected key \'Group\' found in params',

**Comment by ryanmurakami** [comment]
Hi @maniklamba20, Looks like in `create-ec2-instance.js` you just need to change `Group` to `GroupName` in your `params` object.
Hope that works!

**Comment by ryanmurakami** [comment]
Hopefully this fixed it, so I'm closing this issue. Let me know if you still have problems.
