### ISSUE TITLE
Invalid header?

### ISSUE THREAD

**Issue by thejeff77** [ryanmurakami/hbfl#3]
Using node 8.3.0: `> node create-ec2-instance.js`

`
Failed to create instance with: { NetworkingError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at handleRequest (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\http\node.js:42:23)
    at executeSend (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\event_listeners.js:304:29)
    at Request.SEND (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\event_listeners.js:319:9)
    at Request.callListeners (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\sequential_executor.js:101:18)
    at Request.emit (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\cygwin64\home\jblayney\Projects\hbfl\node_modules\aws-sdk\lib\request.js:683:14)
  message: 'The header content contains invalid characters',
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname: 'ec2.us-east-1.amazonaws.com',
  retryable: true,
  time: 2019-02-26T20:34:23.458Z }
`

Following the pluralsight tutorial, here is the code:

```
// Imports
const AWS = require('aws-sdk')
const helpers = require('./helpers')

AWS.config.update({ region: 'us-east-1' })

// Declare local variables
const ec2 = new AWS.EC2()
const sgName = 'hamster_sg'
const keyName = 'hamster_key'

// Do all the things together
createSecurityGroup(sgName)
.then(() => {
  return createKeyPair(keyName)
})
.then(helpers.persistKeyPair)
.then(() => {
  return createInstance(sgName, keyName)
})
.then((data) => {
  console.log('Created instance with:', data)
})
.catch((err) => {
  console.error('Failed to create instance with:', err)
})

// Create functions

function createSecurityGroup (sgName) {
  const params = {
    Description: sgName,
    GroupName: sgName
  }

  return new Promise((resolve, reject) => {
    ec2.createSecurityGroup(params, (err, data) => {
      if (err) reject(err)
      else {
        const params = {
          GroupId: data.GroupId,
          IpPermissions: [
            {
              IpProtocol: 'tcp',
              FromPort: 22,
              ToPort: 22,
              IpRanges: [
                {
                  CidrIp: '0.0.0.0/0'
                }
              ]
            },
            {
              IpProtocol: 'tcp',
              FromPort: 3000,
              ToPort: 3000,
              IpRanges: [
                {
                  CidrIp: '0.0.0.0/0'
                }
              ]
            }
          ]
        }
        ec2.authorizeSecurityGroupIngress(params, (err) => {
          if (err) reject(err)
          else resolve()
        })
      }
    })
  })
}

function createKeyPair (keyName) {
  const params = {
    KeyName: keyName
  }

  return new Promise((resolve, reject) => {
    ec2.createKeyPair(params, (err, data) => {
      if (err) reject(err)
      else resolve(data)
    })
  })
}

function createInstance (sgName, keyName) {
  const params = {
    ImageId: 'ami-04bfee437f38a691e',
    InstanceType: 't2.micro',
    KeyName: keyName,
    MaxCount: 1,
    MinCount: 1,
    SecurityGroups: [
      sgName
    ],
    UserData: 'IyEvYmluL2Jhc2gKY3VybCAtLXNpbGVudCAtLWxvY2F0aW9uIGh0dHBzOi8vcnBtLm5vZGVzb3VyY2UuY29tL3NldHVwXzgueCB8IHN1ZG8gYmFzaCAtCnN1ZG8geXVtIGluc3RhbGwgLXkgbm9kZWpzCnN1ZG8geXVtIGluc3RhbGwgLXkgZ2l0CmdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vcnlhbm11cmFrYW1pL2hiZmwuZ2l0CmNkIGhiZmwKbnBtIGkKbnBtIHJ1biBzdGFydAoK'
  }

  return new Promise((resolve, reject) => {
    ec2.runInstances(params, (err, data) => {
      if (err) reject(err)
      else resolve(data)
    })
  })
}

```

**Comment by thejeff77** [comment]
Looks like this was an issue pasting in values to the `aws configure` command, as it likely received a newline, or something else that was causing the error.

**Comment by ryanmurakami** [comment]
Glad you found the issue!
