### ISSUE TITLE
VPCIdNotSpecified

### ISSUE THREAD

**Issue by MuhammadMoniruzzamanTR** [ryanmurakami/hbfl#40]
hbfl-main\scripts\module_02>node create-ec2-instance.js
Failed to create instance with: VPCIdNotSpecified: No default VPC for this user
    at Request.extractError hbfl-main\node_modules\aws-sdk\lib\services\ec2.js:50:35)
    at Request.callListeners \hbfl-main\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
   )
    at Request.callListeners (Downloads\hbfl-main\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'VPCIdNotSpecified',
  time: 2021-09-10T20:14:32.900Z,
  requestId: 'e1ecfc96-b54d-4802-8f93-3f59ad74ffb1',
  statusCode: 400,
  retryable: false,
  retryDelay: 46.060148016048075

**Comment by ryanmurakami** [comment]
Hi @MuhammadMoniruzzamanTR,

This error is the result of the region you're deploying to not having a default vpc set up. You can follow the instructions here to get that configured in your account: https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html

Hope it helps!
Ryan
