### ISSUE TITLE
Would not spin up EC2 instance

### ISSUE THREAD

**Issue by JDillon522** [ryanmurakami/hbfl#45]
I'm going through the Pluralsight AWS: Designing and Developing course and I had issues spinning this up. After a ton of debugging the UserData I discovered that webpack wasnt running because it wasnt downloading the whole project and that the `bin` dir didnt exist. Apparently its a known issue. I also had to set up Node Forever in order to get it to spin things up. 

I think the root issue is something to do with the `package-lock.json` and webpack. My final working UserData was as follows: 
```
#!/bin/bash
sudo apt-get update
sudo apt-get -y install git
rm -rf /home/bitnami/hbfl
git clone https://github.com/ryanmurakami/hbfl.git /home/bitnami/hbfl
chown -R bitnami: /home/bitnami/hbfl
cd /home/bitnami/hbfl
sudo rm package-lock.json >> /error.txt 2>&1
sudo npm install >> /error.txt 2>&1
sudo npm install -g forever >> /error.txt 2>&1
sudo node node_modules/webpack/bin/webpack.js >> /error.txt 2>&1
sudo forever start index.js >> /error.txt 2>&1
```

Also, I learned after the fact that I didnt need to manually dump to an error file because of the log file at `/var/log/cloud-init-output.log`

Anyhoo, great course. Just wanted to raise this flag.

**Comment by alilinykh** [comment]
Hello! I had the same issue. Instance didn't spin automatically. The solution was pretty simple: add 
"sudo su" to the original userData. Everything works now.
`#!/bin/bash
curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
sudo yum install -y nodejs
sudo yum install -y git
cd home/ec2-user
git clone https://github.com/ryanmurakami/hbfl.git
cd hbfl
**sudo su**
npm i
npm run start`

updated encoded userData: 
"IyEvYmluL2Jhc2gKY3VybCAtLXNpbGVudCAtLWxvY2F0aW9uIGh0dHBzOi8vcnBtLm5vZGVzb3VyY2UuY29tL3NldHVwXzE2LnggfCBzdWRvIGJhc2ggLQpzdWRvIHl1bSBpbnN0YWxsIC15IG5vZGVqcwpzdWRvIHl1bSBpbnN0YWxsIC15IGdpdApjZCBob21lL2VjMi11c2VyCmdpdCBjbG9uZSBodHRwczovL2dpdGh1Yi5jb20vcnlhbm11cmFrYW1pL2hiZmwuZ2l0CmNkIGhiZmwKc3VkbyBzdQpucG0gaQpucG0gcnVuIHN0YXJ0"

**Comment by RyanTsang713** [comment]
we can use yarn instead as well

```
#!/bin/bash
su ec2-user
curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -
sudo yum install -y nodejs
sudo yum install -y git
echo "npm install yarn -g"
sudo npm install yarn -g
echo "end npm install yarn -g"
cd ~
git clone https://github.com/ryanmurakami/hbfl.git
cd hbfl
echo "yarn"
yarn
echo "end yarn"
yarn start

# The above commands base64 encoded for entering into UserData
# IyEvYmluL2Jhc2gKc3UgZWMyLXVzZXIKY3VybCAtLXNpbGVudCAtLWxvY2F0aW9uIGh0dHBzOi8vcnBtLm5vZGVzb3VyY2UuY29tL3NldHVwXzE2LnggfCBzdWRvIGJhc2ggLQpzdWRvIHl1bSBpbnN0YWxsIC15IG5vZGVqcwpzdWRvIHl1bSBpbnN0YWxsIC15IGdpdAplY2hvICJucG0gaW5zdGFsbCB5YXJuIC1nIgpzdWRvIG5wbSBpbnN0YWxsIHlhcm4gLWcKZWNobyAiZW5kIG5wbSBpbnN0YWxsIHlhcm4gLWciCmNkIH4KZ2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9yeWFubXVyYWthbWkvaGJmbC5naXQKY2QgaGJmbAplY2hvICJ5YXJuIgp5YXJuCmVjaG8gImVuZCB5YXJuIgp5YXJuIHN0YXJ0
```

**Comment by ryanmurakami** [comment]
Thanks for sharing! Glad you figured it out! 👍
