### ISSUE TITLE
npm start exit with error

### ISSUE THREAD

**Issue by girishsuri15** [ryanmurakami/hbfl#5]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hbfl@1.0.0 start: `forever stopall && ./node_modules/.bin/forever start index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hbfl@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\girishsuri\AppData\Roaming\npm-cache\_logs\2019-05-17T06_48_50_692Z-debug.lo

**Comment by ryanmurakami** [comment]
Hi @girishsuri15, this error doesn't give me enough to know what the issue is. Can you provide more information?
