### ISSUE TITLE
Users.js and UserFavorites.js point to aurora.client rather than mysql.client

### ISSUE THREAD

**Issue by JACJava** [ryanmurakami/hbfl#8]
Hi Ryan,

I'm doing your Pluralsight AWS Developer:  Designing and Developing and noticed that the Users.js and UserFavorites.js routines throw an error because both modules have this requirement that doesn't exist in the provided code (and wouldn't work anyway since the course calls for a MySQL database):

const client = require('../aurora.client')

Easily fixed by changing it to this:

const client = require('../mysql.client')

Thanks!

**Comment by ryanmurakami** [comment]
Thanks for pointing this out! I've fixed it.
